### ISSUE TITLE
Error 550 Can't create directory: No such file or directory

### ISSUE THREAD

**Issue by pawzy** [evanplaice/node-ftpsync#33]
I am getting the "Error 550 Can't create directory: No such file or directory" error upon committing. The log says that MKDIR failed creating a directory. I have checked the permissions on ftp and as I have made one initial commit to ftp and everything worked I don't think it has anything to do with ftp permissions.

**Comment by mtuchi** [comment]
Me too 
my error logs

`MKDIR failed.
MKDIRs failed.
Commit failed.
{ Error: 550 Create directory operation failed.
    at Ftp.parse (/home/mtuchi/Workspace/C4T-Ed/node_modules/mtuchi_ftpsync/node_modules/jsftp/lib/jsftp.js:223:11)
    at Ftp.parseResponse (/home/mtuchi/Workspace/C4T-Ed/node_modules/mtuchi_ftpsync/node_modules/jsftp/lib/jsftp.js:146:8)
    at Stream.pipeline.on.data (/home/mtuchi/Workspace/C4T-Ed/node_modules/mtuchi_ftpsync/node_modules/jsftp/lib/jsftp.js:112:10)
    at emitOne (events.js:115:13)
    at Stream.emit (events.js:210:7)
    at ResponseParser.reemit (/home/mtuchi/Workspace/C4T-Ed/node_modules/mtuchi_ftpsync/node_modules/duplexer/index.js:70:25)
    at emitOne (events.js:115:13)
    at ResponseParser.emit (events.js:210:7)
    at readableAddChunk (/home/mtuchi/Workspace/C4T-Ed/node_modules/mtuchi_ftpsync/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at ResponseParser.Readable.push (/home/mtuchi/Workspace/C4T-Ed/node_modules/mtuchi_ftpsync/node_modules/readable-stream/lib/_stream_readable.js:162:10) code: 550 }
,

**Comment by mtuchi** [comment]
Any fix for this ? @evanplaice

**Comment by evanplaice** [comment]
Good question. What does your config look like. Are there any file permission issues.

Currently, this tool depends on some outdated JSFTP features. It would be best to workaround those first. My attention is currently devoted to other projects. If you'd like to work on this I'll provide guidance/support. Otherwise, it's going to be on the back burner for a bit.

**Comment by mtuchi** [comment]
My config file look like this
`{
    "local": "assets/storage/",
    "remote": "downloads",
    "host": "10.0.0.1",
    "port": 21,
    "user": "***",
    "pass": "****",
    "connections": "2",
    "ignore": [
        ".htaccess"
    ]
}`

I have a micro controller that i can access on that ip address `10.0.0.1`

**Comment by evanplaice** [comment]
Try starting the relative directories with ./

{ "local": "./assets/storage/", "remote": "./downloads", "host": "10.0.0.1", "port": 21, "user": "***", "pass": "****", "connections": "2", "ignore": [ ".htaccess" ] }

Do the directories have read, write, and list access enabled?

**Comment by mtuchi** [comment]
Still getting the same error.

The file permissions on the remote are 
For downloads
![downloads](https://user-images.githubusercontent.com/6592749/35832600-effc80f6-0ade-11e8-8f3d-f5e1b718474d.png)

For a folder inside downloads
![wiki](https://user-images.githubusercontent.com/6592749/35832620-ffbaca48-0ade-11e8-8745-10e3689861e1.png)

**Comment by evanplaice** [comment]
Try changing permissions on downloads to 666 (rw for user, group, all). It's possible that node is running as a user other than the one you're logged in as. In which case it won't be able to write to downloads.

**Comment by mtuchi** [comment]
The downloads permission are fixed to 755 i can not change that
Do you think that might be the issue ?
