### ISSUE TITLE
TypeError: Object #<Object> has no method 'info'

### ISSUE THREAD

**Issue by paulwellnerbou** [evanplaice/node-ftpsync#8]
I tried ftpsync the first time today, without success. This is my config file:

```
  {
    "local":".",
    "remote":"/FGE/v2/",
    "host":"www.kk-eppstein.de",
    "port":21,
    "user":"www.kk-eppstein.de",
    "pass":"***",
    "connections":"2",
    "ignore":[
      ".scripts", "scss", "bower_components",
      "Bilder", "bower.json", "Gruntfile.js",
      "node_modules", "package.json", "README.md",
      "run.sh", "Dockerfile", "config.json"
    ]
  }
```

And I get this error running ftpsync:

```
$ ftpsync 
Setup
Setup complete.

Collecting
Collection complete.

Consolidating
Consolidation complete.

Committing

/usr/local/lib/node_modules/ftpsync/lib/ftpsync.js:218
          sync.info('MKDIRs complete.');
               ^
TypeError: Object #<Object> has no method 'info'
    at /usr/local/lib/node_modules/ftpsync/lib/ftpsync.js:218:16
    at /usr/local/lib/node_modules/ftpsync/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/ftpsync/node_modules/async/lib/async.js:203:33
    at /usr/local/lib/node_modules/ftpsync/node_modules/async/lib/async.js:251:21
    at Array.1 (/usr/local/lib/node_modules/ftpsync/lib/ftpsync.js:437:7)
    at Ftp.parse (/usr/local/lib/node_modules/ftpsync/node_modules/jsftp/lib/jsftp.js:241:13)
    at Ftp.parseResponse (/usr/local/lib/node_modules/ftpsync/node_modules/jsftp/lib/jsftp.js:158:8)
    at Stream.<anonymous> (/usr/local/lib/node_modules/ftpsync/node_modules/jsftp/lib/jsftp.js:129:24)
    at Stream.EventEmitter.emit (events.js:95:17)
    at ResponseParser.reemit (/usr/local/lib/node_modules/ftpsync/node_modules/jsftp/node_modules/event-stream/node_modules/duplexer/index.js:70:25)
```

Am I doing something wrong?

**Comment by evanplaice** [comment]
Probably not. The logging module had some significant changes that aren't covered under testing yet. It's probably just a minor bug.

I'll look into it.

**Comment by evanplaice** [comment]
I can't seem to reproduce the issue.

I looked at the source. There's nothing near line 218 that looks off. I ran the latest against my functional test (ie unit testing doesn't work because there's no way to mock a ftp server) without issue.

I'm going to close for now. If you try again and run into issues, don't hesitate to repoen.
